// ACORDATE: Cambiá este número cada vez que agregues o modifiques un archivo
const CACHE_NAME = 'cancionero-v4'; 

// LA LISTA GIGANTE (Acá tenés que poner TODO)
const urlsToCache = [
  // 1. Lo principal
  '/cancionerobenja/',
  '/cancionerobenja/index.html',
  '/cancionerobenja/navbar.html',
  '/cancionerobenja/css/cancionero.css',
  '/cancionerobenja/scripts/cancionero.js',
  '/cancionerobenja/images/logo-schoenstatt-png.png',
  '/cancionerobenja/images/foto-cpk.jpg', 
  '/cancionerobenja/crear-programa.html',

  // 1.1. Secciones
  '/cancionerobenja/01-entrada.html',
    '/cancionerobenja/02-perdon.html',
    '/cancionerobenja/03-gloria.html',
    '/cancionerobenja/04-salmos.html',
    '/cancionerobenja/05-aleluya.html',
    '/cancionerobenja/06-ofertorio.html',
    '/cancionerobenja/07-santo.html',
    '/cancionerobenja/08-padrenuestro.html',
    '/cancionerobenja/09-cordero.html',
    '/cancionerobenja/10-comunion.html',
    '/cancionerobenja/11-meditacion.html',
    '/cancionerobenja/12-salida.html',
    '/cancionerobenja/13-marianos.html',
    '/cancionerobenja/14-envio.html',
    '/cancionerobenja/15-espiritu-santo.html',
    '/cancionerobenja/16-adoracion.html',
    '/cancionerobenja/17-jm.html',
    '/cancionerobenja/18-jf.html',
    '/cancionerobenja/19-indice-alfabetico.html',
    '/cancionerobenja/20-albumes.html',
  
  // 2. Las páginas de los álbumes
  '/cancionerobenja/20-albumes.html',
  '/cancionerobenja/albumes/tierra-nueva-de-la-trinidad.html',
  '/cancionerobenja/albumes/quiero-construirte-una-casa-señor.html',
  '/cancionerobenja/albumes/hoy-quiero-cantarte.html',
  '/cancionerobenja/albumes/santuario-corazon.html',
  '/cancionerobenja/albumes/como-un-niño.html',
  '/cancionerobenja/albumes/porta.html',
  '/cancionerobenja/albumes/ciudad-multicor.html',
  '/cancionerobenja/albumes/en-tus-ojos.html',
  '/cancionerobenja/albumes/queda-entre-nosotros.html',
  '/cancionerobenja/albumes/para-darlo-a-los-demas.html',
  '/cancionerobenja/albumes/tiempo-de-alianza.html',
  '/cancionerobenja/albumes/contigo-+-feliz.html',
  '/cancionerobenja/albumes/nos-junta-el-sol.html',
  '/cancionerobenja/albumes/jm-argentina.html',
  '/cancionerobenja/albumes/vive-dios.html',
  '/cancionerobenja/albumes/berit-1.html',
  '/cancionerobenja/albumes/berit-2.html',
  '/cancionerobenja/albumes/de-peregrinos-y-mediodias.html',
  '/cancionerobenja/albumes/vengan-a-mi.html',

  // 3. Las portadas de los álbumes (¡VITAL PARA QUE SE VEAN!)
  '/cancionerobenja/albumes/files/portada-tierra-nueva-de-la-trinidad.jpg',
'/cancionerobenja/albumes/files/portada-quiero-construirte-una-casa-señor.jpg',
'/cancionerobenja/albumes/files/portada-hoy-quiero-cantarte.jpg',
'/cancionerobenja/albumes/files/portada-santuario-corazon.jpg',
'/cancionerobenja/albumes/files/portada-como-un-niño.jpg',
'/cancionerobenja/albumes/files/portada-porta.jpg',
'/cancionerobenja/albumes/files/portada-ciudad-multicor.jpg',
'/cancionerobenja/albumes/files/portada-en-tus-ojos.jpg',
'/cancionerobenja/albumes/files/portada-queda-entre-nosotros.jpg',
'/cancionerobenja/albumes/files/portada-para-darlo-a-los-demas.jpg',
'/cancionerobenja/albumes/files/portada-tiempo-de-alianza.jpg',
'/cancionerobenja/albumes/files/portada-contigo-+-feliz.jpg',
'/cancionerobenja/albumes/files/portada-nos-junta-el-sol.jpg',
'/cancionerobenja/albumes/files/portada-jm-argentina.jpg',
'/cancionerobenja/albumes/files/portada-vive-dios.jpg',
'/cancionerobenja/albumes/files/portada-berit-1.jpg',
'/cancionerobenja/albumes/files/portada-berit-2.jpg',
'/cancionerobenja/albumes/files/portada-de-peregrinos-y-mediodias.jpg',
'/cancionerobenja/albumes/files/portada-vengan-a-mi.jpg',

  // 4. Las canciones individuales
  '/cancionerobenja/meditacion/a-el-la-gloria.html',
'/cancionerobenja/marianos/a-tanto-amor.html',
'/cancionerobenja/meditacion/a-ti-te-alabo.html',
'/cancionerobenja/meditacion/abramos.html',
'/cancionerobenja/marianos/abrazada-a-ti-en-tu-cruz.html',
'/cancionerobenja/comunion/abre.html',
'/cancionerobenja/meditacion/acogeme.html',
'/cancionerobenja/comunion/acuerdate-de-mi.html',
'/cancionerobenja/comunion/al-servicio-de-aquel.html',
'/cancionerobenja/adoracion/alabado-sea-el-santisimo.html',
'/cancionerobenja/meditacion/alabenlo.html',
'/cancionerobenja/aleluya/aleluya-busca-primero.html',
'/cancionerobenja/aleluya/aleluya-cada-palabra.html',
'/cancionerobenja/aleluya/aleluya-cantad-alegres.html',
'/cancionerobenja/aleluya/aleluya-comun.html',
'/cancionerobenja/aleluya/aleluya-cuaresma.html',
'/cancionerobenja/aleluya/aleluya-jlg.html',
'/cancionerobenja/aleluya/aleluya-yo-soy-el-maestro.html',
'/cancionerobenja/meditacion/algo-de-paz.html',
'/cancionerobenja/ofertorio/alimento-que-da-vida.html',
'/cancionerobenja/meditacion/alma-de-cristo.html',
'/cancionerobenja/comunion/alma-misionera.html',
'/cancionerobenja/comunion/alza-mi-paz.html',
'/cancionerobenja/comunion/alzar-banderas.html',
'/cancionerobenja/meditacion/amanecer.html',
'/cancionerobenja/meditacion/amigo.html',
'/cancionerobenja/comunion/apareces.html',
'/cancionerobenja/meditacion/apostol-de-jesucristo.html',
'/cancionerobenja/meditacion/arde.html',
'/cancionerobenja/salida/avanza-reina.html',
'/cancionerobenja/salida/ave-maria.html',
'/cancionerobenja/meditacion/baja-hasta-lo-mas-hondo.html',
'/cancionerobenja/meditacion/barro-soy.html',
'/cancionerobenja/meditacion/cae-el-agua.html',
'/cancionerobenja/comunion/caminando.html',
'/cancionerobenja/meditacion/caminho-de-eternidade.html',
'/cancionerobenja/comunion/camino-verdad-y-vida.html',
'/cancionerobenja/comunion/cantaro-niño.html',
'/cancionerobenja/meditacion/cara-a-cara.html',
'/cancionerobenja/meditacion/cayado-de-amor.html',
'/cancionerobenja/entrada/celebremos.html',
'/cancionerobenja/comunion/cena-de-jueves.html',
'/cancionerobenja/ofertorio/cinco-panes.html',
'/cancionerobenja/comunion/clarifica-te.html',
'/cancionerobenja/ofertorio/comenzaste-a-hacerte-pan.html',
'/cancionerobenja/comunion/como-antes-mas-que-antes.html',
'/cancionerobenja/comunion/como-un-niño.html',
'/cancionerobenja/comunion/con-vos.html',
'/cancionerobenja/meditacion/confiare-en-tu-amor.html',
'/cancionerobenja/meditacion/conozco-tu-corazon.html',
'/cancionerobenja/jm/corazon-de-fuego.html',
'/cancionerobenja/cordero/cordero1.html',
'/cancionerobenja/cordero/cordero2.html',
'/cancionerobenja/cordero/cordero3.html',
'/cancionerobenja/cordero/cordero4.html',
'/cancionerobenja/cordero/cordero5.html',
'/cancionerobenja/comunion/creemos-oh-dios.html',
'/cancionerobenja/meditacion/cristo-calla.html',
'/cancionerobenja/entrada/cristo-joven.html',
'/cancionerobenja/meditacion/cristo-reina.html',
'/cancionerobenja/meditacion/cristo-rey.html',
'/cancionerobenja/comunion/dame-tu-si.html',
'/cancionerobenja/meditacion/dame-tus-ojos.html',
'/cancionerobenja/comunion/de-cirene.html',
'/cancionerobenja/entrada/deja-que-nazca.html',
'/cancionerobenja/comunion/dejate.html',
'/cancionerobenja/meditacion/derrama.html',
'/cancionerobenja/comunion/despues-de-caer.html',
'/cancionerobenja/meditacion/digno-de-alabar.html',
'/cancionerobenja/meditacion/dime-rey.html',
'/cancionerobenja/salida/dios-te-salve.html',
'/cancionerobenja/comunion/ego-paulus.html',
'/cancionerobenja/marianos/el-diario-de-maria.html',
'/cancionerobenja/entrada/el-dios-de-la-vida.html',
'/cancionerobenja/meditacion/el-me-miro.html',
'/cancionerobenja/meditacion/el-mismo-huerto.html',
'/cancionerobenja/entrada/el-pulso-de-dios.html',
'/cancionerobenja/comunion/el-que-muere-por-mi.html',
'/cancionerobenja/comunion/el-sale-a-tu-encuentro.html',
'/cancionerobenja/comunion/emaus.html',
'/cancionerobenja/entrada/en-el-nombre-de-dios.html',
'/cancionerobenja/comunion/en-mi-getsemani.html',
'/cancionerobenja/meditacion/en-la-palma-de-su-mano.html',
'/cancionerobenja/meditacion/en-ti.html',
'/cancionerobenja/meditacion/en-ti-descansar.html',
'/cancionerobenja/meditacion/en-tu-misericordia.html',
'/cancionerobenja/comunion/en-tus-ojos.html',
'/cancionerobenja/comunion/enciende-nuestra-mision.html',
'/cancionerobenja/comunion/eres.html',
'/cancionerobenja/comunion/es-aqui.html',
'/cancionerobenja/meditacion/esa-flor-siempre-de-pie.html',
'/cancionerobenja/comunion/escalva-de-mi-salvador.html',
'/cancionerobenja/meditacion/escuchame-dios.html',
'/cancionerobenja/meditacion/esperanza.html',
'/cancionerobenja/espiritu-santo/espiritu-santo.html',
'/cancionerobenja/espiritu-santo/espiritu-desciende.html',
'/cancionerobenja/comunion/estamos-aqui.html',
'/cancionerobenja/comunion/estandarte.html',
'/cancionerobenja/meditacion/estar-con-el.html',
'/cancionerobenja/salida/este-es-mi-hogar.html',
'/cancionerobenja/ofertorio/esto-que-soy-esto-te-doy.html',
'/cancionerobenja/salmos/exodo-15.html',
'/cancionerobenja/meditacion/extiende-tu-mano.html',
'/cancionerobenja/meditacion/extranjeros.html',
'/cancionerobenja/comunion/frente-a-ti.html',
'/cancionerobenja/espiritu-santo/fuego-santo.html',
'/cancionerobenja/jf/generacion-fundadora.html',
'/cancionerobenja/gloria/gloria-1.html',
'/cancionerobenja/gloria/gloria-2.html',
'/cancionerobenja/gloria/gloria-3.html',
'/cancionerobenja/gloria/gloria-4.html',
'/cancionerobenja/comunion/ha-sido-largo-el-viaje.html',
'/cancionerobenja/comunion/hagase-mi-paz.html',
'/cancionerobenja/meditacion/hago-nuevas-todas-las-cosas.html',
'/cancionerobenja/comunion/hasta-que-el-mundo-arda-por-el.html',
'/cancionerobenja/salida/hay-un-rio-de-vida.html',
'/cancionerobenja/meditacion/haz-llover.html',
'/cancionerobenja/jm/herencia.html',
'/cancionerobenja/meditacion/hijo-amado.html',
'/cancionerobenja/meditacion/hoy-quiero-mirarte.html',
'/cancionerobenja/comunion/hoy-vivo.html',
'/cancionerobenja/meditacion/huracan.html',
'/cancionerobenja/salida/ignis-mariae.html',
'/cancionerobenja/meditacion/jesus.html',
'/cancionerobenja/meditacion/jesus-berit2.html',
'/cancionerobenja/comunion/jesus-y-pedro.html',
'/cancionerobenja/salida/junto-a-ti-maria.html',
'/cancionerobenja/ofertorio/juntos-nos-acercamos.html',
'/cancionerobenja/comunion/juremos-con-gloria-morir.html',
'/cancionerobenja/salida/la-de-siempre.html',
'/cancionerobenja/meditacion/la-luz-de-jesus.html',
'/cancionerobenja/comunion/la-niña-de-tus-ojos.html',
'/cancionerobenja/comunion/labor-del-apostol.html',
'/cancionerobenja/gloria/letanias.html',
'/cancionerobenja/meditacion/llevame-a-la-cruz-nadie-igual.html',
'/cancionerobenja/meditacion/lo-que-importa-es-el-amor.html',
'/cancionerobenja/meditacion/magnificat.html',
'/cancionerobenja/comunion/mais-longe.html',
'/cancionerobenja/salida/mar-adentro.html',
'/cancionerobenja/espiritu-santo/maranatha.html',
'/cancionerobenja/meditacion/maravillas-hizo-en-mi.html',
'/cancionerobenja/marianos/maria-servus-mariae.html',
'/cancionerobenja/salida/maria-de-la-alianza.html',
'/cancionerobenja/marianos/maria-esta-pasando-por-aqui.html',
'/cancionerobenja/comunion/maria-madre.html',
'/cancionerobenja/comunion/maria-tierra-del-padre.html',
'/cancionerobenja/comunion/maria-vai.html',
'/cancionerobenja/comunion/mas-alla-del-mar.html',
'/cancionerobenja/meditacion/me-llamaste-amigo.html',
'/cancionerobenja/meditacion/me-quieres.html',
'/cancionerobenja/meditacion/mi-110.html',
'/cancionerobenja/meditacion/mi-alma-descansa-en-ti.html',
'/cancionerobenja/meditacion/mi-entrega-a-ti.html',
'/cancionerobenja/meditacion/milagro-de-amor.html',
'/cancionerobenja/salida/misioneros.html',
'/cancionerobenja/meditacion/nada-te-turbe.html',
'/cancionerobenja/meditacion/nadie-te-ama-como-yo.html',
'/cancionerobenja/comunion/no-hay-amor-mas-grande.html',
'/cancionerobenja/meditacion/no-mueras-hermano.html',
'/cancionerobenja/meditacion/no-os-preocupeis.html',
'/cancionerobenja/comunion/no-temas.html',
'/cancionerobenja/meditacion/no-tienen-vino.html',
'/cancionerobenja/meditacion/noche.html',
'/cancionerobenja/comunion/nuestra-alianza.html',
'/cancionerobenja/ofertorio/nuestra-fe-en-tu-amor.html',
'/cancionerobenja/ofertorio/oh-padre.html',
'/cancionerobenja/ofertorio/oh-señor.html',
'/cancionerobenja/meditacion/oracion-de-confianza.html',
'/cancionerobenja/marianos/oracion-de-consagracion.html',
'/cancionerobenja/jm/oracion-de-franz-reinisch.html',
'/cancionerobenja/padrenuestro/padrenuestro.html',
'/cancionerobenja/ofertorio/para-darlo-a-los-demas.html',
'/cancionerobenja/comunion/para-que-todos-tengan-vida.html',
'/cancionerobenja/comunion/pasion-que-transforma.html',
'/cancionerobenja/meditacion/paz.html',
'/cancionerobenja/perdon/perdon-1.html',
'/cancionerobenja/perdon/perdon-2.html',
'/cancionerobenja/perdon/perdon-3-renuevame.html',
'/cancionerobenja/perdon/perdon-4-una-vez-mas-rezare.html',
'/cancionerobenja/perdon/perdon-5-dejame-nacer.html',
'/cancionerobenja/comunion/perfume-a-tus-pies.html',
'/cancionerobenja/meditacion/permanecer-en-ti.html',
'/cancionerobenja/comunion/pescador-de-hombres.html',
'/cancionerobenja/meditacion/por-que-lloras.html',
'/cancionerobenja/meditacion/por-un-solo-momento.html',
'/cancionerobenja/gloria/pregon-pascual.html',
'/cancionerobenja/meditacion/puer-et-pater.html',
'/cancionerobenja/espiritu-santo/que-se-abra-el-cielo.html',
'/cancionerobenja/comunion/quedate-señor.html',
'/cancionerobenja/meditacion/quiero-adorarte.html',
'/cancionerobenja/meditacion/quiero-ser-santo.html',
'/cancionerobenja/comunion/quiero-ser-tu-amigo-jesucristo.html',
'/cancionerobenja/meditacion/regalanos.html',
'/cancionerobenja/salida/reina-de-mi-corazon.html',
'/cancionerobenja/marianos/reina-y-madre.html',
'/cancionerobenja/comunion/renace-la-vida-y-el-corazon.html',
'/cancionerobenja/meditacion/restauranos.html',
'/cancionerobenja/comunion/sal-y-luz.html',
'/cancionerobenja/salmos/salmo-18.html',
'/cancionerobenja/salmos/salmo-28.html',
'/cancionerobenja/salmos/salmo-30.html',
'/cancionerobenja/salmos/salmo-34.html',
'/cancionerobenja/salmos/salmo-41.html',
'/cancionerobenja/salmos/salmo-103.html',
'/cancionerobenja/salmos/salmo-115.html',
'/cancionerobenja/salmos/salmo-117.html',
'/cancionerobenja/meditacion/saname.html',
'/cancionerobenja/santo/santo1.html',
'/cancionerobenja/santo/santo2.html',
'/cancionerobenja/santo/santo3.html',
'/cancionerobenja/santo/santo4.html',
'/cancionerobenja/santo/santo5.html',
'/cancionerobenja/santo/santo6.html',
'/cancionerobenja/santo/santo7.html',
'/cancionerobenja/comunion/se-en-quien-he-puesto-mi-confianza.html',
'/cancionerobenja/marianos/se-llama-maria.html',
'/cancionerobenja/comunion/sentidos.html',
'/cancionerobenja/meditacion/señor-de-la-paz.html',
'/cancionerobenja/comunion/sera-dios.html',
'/cancionerobenja/comunion/si-quieres-te-acompaño-en-el-camino.html',
'/cancionerobenja/meditacion/si-rasgaras.html',
'/cancionerobenja/meditacion/siempre-has-sido-tu.html',
'/cancionerobenja/comunion/siempre-para-ti.html',
'/cancionerobenja/meditacion/sigueme.html',
'/cancionerobenja/comunion/silencio-en-el-calvario.html',
'/cancionerobenja/meditacion/silencio-en-la-cruz.html',
'/cancionerobenja/meditacion/silencio-fecundo.html',
'/cancionerobenja/comunion/sin-fronteras.html',
'/cancionerobenja/salida/sobre-el-mar.html',
'/cancionerobenja/comunion/sobre-el-mar-berit2.html',
'/cancionerobenja/meditacion/soledad.html',
'/cancionerobenja/meditacion/solo-por-hoy.html',
'/cancionerobenja/meditacion/solo-tu.html',
'/cancionerobenja/comunion/somos-jm-somos-iglesia.html',
'/cancionerobenja/comunion/soñar.html',
'/cancionerobenja/meditacion/sopla.html',
'/cancionerobenja/meditacion/stabat.html',
'/cancionerobenja/meditacion/su-canto.html',
'/cancionerobenja/meditacion/subido-al-sicomoro.html',
'/cancionerobenja/meditacion/supe-que-me-amabas.html',
'/cancionerobenja/meditacion/surge-valentia.html',
'/cancionerobenja/jf/talita-kum.html',
'/cancionerobenja/meditacion/tambien-hoy.html',
'/cancionerobenja/aleluya/te-adoramos-cristo.html',
'/cancionerobenja/meditacion/te-alabo.html',
'/cancionerobenja/meditacion/te-encontre.html',
'/cancionerobenja/comunion/te-estaba-esperando.html',
'/cancionerobenja/comunion/te-veo.html',
'/cancionerobenja/meditacion/tempestad.html',
'/cancionerobenja/ofertorio/toma-señor.html',
'/cancionerobenja/ofertorio/tomame.html',
'/cancionerobenja/meditacion/torrente-de-vida.html',
'/cancionerobenja/meditacion/transforma-mi-casa-en-tu-hogar.html',
'/cancionerobenja/meditacion/transformacion-en-pentecostes.html',
'/cancionerobenja/comunion/tu-amor.html',
'/cancionerobenja/meditacion/tu-el-unico-rey.html',
'/cancionerobenja/meditacion/tu-estas-aqui-de-tal-manera.html',
'/cancionerobenja/comunion/tu-luz.html',
'/cancionerobenja/meditacion/tu-luz.html',
'/cancionerobenja/meditacion/tu-modo.html',
'/cancionerobenja/aleluya/tu-palabra-señor-es-la-verdad.html',
'/cancionerobenja/meditacion/tu-voluntad.html',
'/cancionerobenja/meditacion/tu-voluntad-servus.html',
'/cancionerobenja/entrada/un-nuevo-sol.html',
'/cancionerobenja/meditacion/una-cuerda-menos.html',
'/cancionerobenja/comunion/una-gota-de-agua.html',
'/cancionerobenja/meditacion/velad-por-mi.html',
'/cancionerobenja/espiritu-santo/ven-espiritu-de-amor.html',
'/cancionerobenja/espiritu-santo/ven-espiritu-divino.html',
'/cancionerobenja/espiritu-santo/ven-espiritu-santo.html',
'/cancionerobenja/comunion/ven-jesus-de-nazareth.html',
'/cancionerobenja/comunion/ven-pastor.html',
'/cancionerobenja/meditacion/ven-y-sigueme.html',
'/cancionerobenja/meditacion/ven-y-veras.html',
'/cancionerobenja/meditacion/vengan-a-mi.html',
'/cancionerobenja/comunion/vengan-y-coman.html',
'/cancionerobenja/meditacion/vengo-a-adorarte.html',
'/cancionerobenja/meditacion/veras-cosas-mayores.html',
'/cancionerobenja/comunion/vida-en-abundancia.html',
'/cancionerobenja/espiritu-santo/viento-de-dios.html',
'/cancionerobenja/meditacion/vivir-amando.html',
'/cancionerobenja/espiritu-santo/voces-de-esperanza.html',
'/cancionerobenja/meditacion/vuelve-a-mi.html',
'/cancionerobenja/meditacion/vuelvo-a-ti.html',
'/cancionerobenja/comunion/ya-es-hora.html',
'/cancionerobenja/comunion/yo-soy-el-mar.html',

//4.1. Canciones de albumes
'/cancionerobenja/tierra-nueva-de-la-trinidad/agradecimiento.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/señor-de-mi-barca.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/cristo-del-calvario.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/hacia-ti.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/estas-dentro-de-mi.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/espiritu-santo-hacia-el-padre.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/tierra-nueva-de-la-trinidad.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/quien-me-quiera-seguir.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/confio.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/madre-aqui-estoy.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/solo-basta-dios.html',
'/cancionerobenja/tierra-nueva-de-la-trinidad/por-ti-hija-de-sion.html',

'/cancionerobenja/quiero-construirte-una-casa-señor/quiero-construirte-una-casa-señor.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/desierto.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/quien-eres-tu.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/madre-aqui-estoy.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/mi-señor-mi-dios.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/ofrenda.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/venid-a-mi.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/siervo-de-dios.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/ven-y-veras.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/pasas-madre.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/encuentro.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/con-la-vuelta-del-sol.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/pastor-y-cordero.html',
'/cancionerobenja/quiero-construirte-una-casa-señor/si-pudiera.html',

'/cancionerobenja/porta/de-una-historia-entre-dos.html',
'/cancionerobenja/porta/confia.html',
'/cancionerobenja/porta/entrega.html',
'/cancionerobenja/porta/maria-luz-de-esperanza.html',
'/cancionerobenja/porta/contigo-maria.html',

  // 5. Librerías externas
  'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js',
  'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js'
];

// --- 1. INSTALACIÓN ANTI-BOMBAS ---
// En vez de cancelar todo si hay un error de tipeo, 
// descarga una por una y si una falla, la ignora y sigue con el resto.
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      console.log('Empezando a descargar la lista gigante...');
      return Promise.all(
        urlsToCache.map(url => {
          return cache.add(url).catch(error => {
            console.error('Che, esta ruta falló y no se guardó:', url);
          });
        })
      );
    })
  );
});

// --- 2. INTERCEPTOR (CON SALVAVIDAS PARA SAFARI) ---
self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => {
        // Si está en la mochila, lo devuelve
        if (response) {
          return response; 
        }

        // Si no está, va a internet
        return fetch(event.request).then(networkResponse => {
          if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
            return networkResponse;
          }
          const responseToCache = networkResponse.clone();
          caches.open(CACHE_NAME)
            .then(cache => {
              cache.put(event.request, responseToCache);
            });
          return networkResponse;
          
        }).catch(() => {
          // EL SALVAVIDAS: Si no hay internet y no estaba en la mochila, 
          // le devolvemos una mini página a Safari para que no tire el error "null".
          return new Response(
            '<div style="text-align:center; padding:50px; font-family:sans-serif;">' +
            '<h2>¡Ups! Estás sin internet</h2>' +
            '<p>Y parece que esta canción todavía no se guardó en el celular.</p>' +
            '<a href="/cancionerobenja/">Volver al inicio</a></div>',
            { headers: { 'Content-Type': 'text/html; charset=utf-8' } }
          );
        });
      })
  );
});