const canciones = {
    "Entrada": {
        "Alma misionera": { ruta: "entrada/alma-misionera.html", tono: "MI" },
        "Celebremos": { ruta: "entrada/celebremos.html", tono: "DO" },
        "Cristo Joven": { ruta: "entrada/cristo-joven.html", tono: "DO" },
        "Deja que nazca": { ruta: "entrada/deja-que-nazca.html", tono: "MI" },
        "El Dios de la vida": { ruta: "entrada/el-dios-de-la-vida.html", tono: "DO" },
        "El pulso de Dios": { ruta: "entrada/el-pulso-de-dios.html", tono: "MI" },
        "En el nombre de Dios": { ruta: "entrada/en-el-nombre-de-dios.html", tono: "DO" },
        "Un nuevo sol": { ruta: "entrada/un-nuevo-sol.html", tono: "MI" }
    },
    "Perdón": {
        "Perdón 1 (Señor ten piedad)": { ruta: "perdon/perdon-1.html", tono: "DO" },
        "Perdón 2 (Perdón Señor)": { ruta: "perdon/perdon-2.html", tono: "SOL" },
        "Perdón 3 (Renuevame)": { ruta: "perdon/perdon-3-renuevame.html", tono: "DO" },
        "Perdón 4 (Una vez más rezaré)": { ruta: "perdon/perdon-4-una-vez-mas-rezare.html", tono: "RE" },
        "Perdón 5 (Dejame nacer)": { ruta: "perdon/perdon-5-dejame-nacer.html", tono: "DO" }
    },
    "Gloria": {
        "Gloria 1 (Clásico)": { ruta: "gloria/gloria-1.html", tono: "RE" },
        "Gloria 2 (con respuesta)": { ruta: "gloria/gloria-2.html", tono: "DO" },
        "Gloria 3 (Litúrgico)": { ruta: "gloria/gloria-3.html", tono: "DO" }
    },
    "Salmos": {
        "Salmo 18": { ruta: "salmos/salmo-18.html", tono: "LA" },
        "Salmo 28": { ruta: "salmos/salmo-28.html", tono: "LA" },
        "Salmo 34": { ruta: "salmos/salmo-34.html", tono: "MI" }
    },
    "Aleluya": {
        "Aleluya (busca primero)": { ruta: "aleluya/aleluya-busca-primero.html", tono: "LA" },
        "Aleluya (cada palabra)": { ruta: "aleluya/aleluya-cada-palabra.html", tono: "MI" },
        "Aleluya (cantad alegres)": { ruta: "aleluya/aleluya-cantad-alegres.html", tono: "DO" },
        "Aleluya (común)": { ruta: "aleluya/aleluya-comun.html", tono: "LA" },
        "Aleluya (cuaresma)": { ruta: "aleluya/aleluya-cuaresma.html", tono: "DO" },
        "Aleluya (JLG)": { ruta: "aleluya/aleluya-jlg.html", tono: "SOL" },
        "Aleluya (yo soy el maestro)": { ruta: "aleluya/aleluya-yo-soy-el-maestro.html", tono: "MI" }
    },
    "Ofertorio": {
        "Alimento que da vida": { ruta: "ofertorio/alimento-que-da-vida.html", tono: "RE" },
        "Cinco panes y dos peces": { ruta: "ofertorio/cinco-panes.html", tono: "SOL" },
        "Comenzaste a hacerte pan": { ruta: "ofertorio/comenzaste-a-hacerte-pan.html", tono: "DO" },
        "Esto que soy, esto te doy": { ruta: "ofertorio/esto-que-soy-esto-te-doy.html", tono: "SOL" },
        "Juntos nos acercamos": { ruta: "ofertorio/juntos-nos-acercamos.html", tono: "SOL" },
        "Nuestra fe en tu amor": { ruta: "ofertorio/nuestra-fe-en-tu-amor.html", tono: "LA" },
        "Oh Padre": { ruta: "ofertorio/oh-padre.html", tono: "DO" },
        "Oh Señor": { ruta: "ofertorio/oh-señor.html", tono: "MI" },
        "Para darlo a los demas": { ruta: "ofertorio/para-darlo-a-los-demas.html", tono: "RE" },
        "Toma Señor": { ruta: "ofertorio/toma-señor.html", tono: "MI" },
        "Tomame": { ruta: "ofertorio/tomame.html", tono: "LA" }
    },
    "Santo": {
        "Santo 1 (Hacia el Padre)": { ruta: "santo/santo1.html", tono: "DO" },
        "Santo 2 (Hosanna)": { ruta: "santo/santo2.html", tono: "SOL" },
        "Santo 3 (Clásico)": { ruta: "santo/santo3.html", tono: "DO" },
        "Santo 4 (Nuevo)": { ruta: "santo/santo4.html", tono: "RE" },
        "Santo 5 (Saaanto)": { ruta: "santo/santo5.html", tono: "LA" }
    },
    "Padrenuestro": {
        "Padrenuestro": { ruta: "padrenuestro/padrenuestro.html", tono: "RE" }
    },
    "Cordero": {
        "Cordero 1 (Clásico)": { ruta: "cordero/cordero1.html", tono: "DO" },
        "Cordero 2 (Movido)": { ruta: "cordero/cordero2.html", tono: "FA" },
        "Cordero 3 (Dios de amor)": { ruta: "cordero/cordero3.html", tono: "SOL" },
        "Cordero 4 (Zamba)": { ruta: "cordero/cordero4.html", tono: "MI" },
        "Cordero 5 (Lento)": { ruta: "cordero/cordero5.html", tono: "SOL" }
    },
    "Comunión": {
        "Abre": { ruta: "comunion/abre.html", tono: "LA" },
        "Al servicio de aquel": { ruta: "comunion/al-servicio-de-aquel.html", tono: "SOL" },
        "Alma misionera": { ruta: "entrada/alma-misionera.html", tono: "MI" },
        "Alza mi paz": { ruta: "comunion/alza-mi-paz.html", tono: "DO" },
        "Alzar banderas": { ruta: "comunion/alzar-banderas.html", tono: "DO" },
        "Apareces": { ruta: "comunion/apareces.html", tono: "DO" },
        "Camino, verdad y vida": { ruta: "comunion/camino-verdad-y-vida.html", tono: "DO" },
        "Cantaro niño": { ruta: "comunion/cantaro-niño.html", tono: "RE" },
        "Cena de jueves": { ruta: "comunion/cena-de-jueves.html", tono: "FA" },
        "Como antes, más que antes": { ruta: "comunion/como-antes-mas-que-antes.html", tono: "RE" },
        "Como un niño": { ruta: "comunion/como-un-niño.html", tono: "SOL" },
        "Con vos": { ruta: "comunion/con-vos.html", tono: "MI" },
        "De Cirene": { ruta: "comunion/de-cirene.html", tono: "LA" },
        "Dejate": { ruta: "comunion/dejate.html", tono: "DO" },
        "Después de caer": { ruta: "comunion/despues-de-caer.html", tono: "LA" },
        "Ego Paulus": { ruta: "comunion/ego-paulus.html", tono: "SOL" },
        "El que muere por mi": { ruta: "comunion/el-que-muere-por-mi.html", tono: "DO" },
        "El sale a tu encuentro": { ruta: "comunion/el-sale-a-tu-encuentro.html", tono: "MI" },
        "En mi Getsemani": { ruta: "comunion/en-mi-getsemani.html", tono: "DO" },
        "En tus ojos": { ruta: "comunion/en-tus-ojos.html", tono: "SOL" },
        "Enciende nuestra misión": { ruta: "comunion/enciende-nuestra-mision.html", tono: "MI" },
        "Es aquí": { ruta: "comunion/es-aqui.html", tono: "RE" },
        "Estamos aquí": { ruta: "comunion/estamos-aqui.html", tono: "SOL" },
        "Estandarte": { ruta: "comunion/estandarte.html", tono: "RE" },
        "Frente a ti": { ruta: "comunion/frente-a-ti.html", tono: "SOL" },
        "Ha sido largo el viaje": { ruta: "comunion/ha-sido-largo-el-viaje.html", tono: "MI" },
        "Hagase mi paz": { ruta: "comunion/hagase-mi-paz.html", tono: "MI" },
        "Hasta que el mundo arda por El": { ruta: "comunion/hasta-que-el-mundo-arda-por-el.html", tono: "LA" },
        "Hoy vivo": { ruta: "comunion/hoy-vivo.html", tono: "RE" },
        "Jesús y Pedro": { ruta: "comunion/jesus-y-pedro.html", tono: "DO"},
        "Juremos con gloria morir": { ruta: "comunion/juremos-con-gloria-morir.html", tono: "SOL" },
        "La niña de tus ojos": { ruta: "comunion/la-niña-de-tus-ojos.html", tono: "MI" },
        "Labor del apostol": { ruta: "comunion/labor-del-apostol.html", tono: "DO" },
        "María Madre": { ruta: "comunion/maria-madre.html", tono: "MI" },
        "María tierra del Padre": { ruta: "comunion/maria-tierra-del-padre.html", tono: "LA" },
        "María vai": { ruta: "comunion/maria-vai.html", tono: "DO" },
        "Más allá del mar": { ruta: "comunion/mas-alla-del-mar.html", tono: "MI" },
        "No hay amor más grande": { ruta: "comunion/no-hay-amor-mas-grande.html", tono: "DO" },
        "No temas": { ruta: "comunion/no-temas.html", tono: "MI" },
        "Nuestra alianza": { ruta: "comunion/nuestra-alianza.html", tono: "MI" },
        "Para que todos tengan vida": { ruta: "comunion/para-que-todos-tengan-vida.html", tono: "DO" },
        "Pasión que transforma": { ruta: "comunion/pasion-que-transforma.html", tono: "RE" },
        "Pescador de hombres": { ruta: "comunion/pescador-de-hombres.html", tono: "DO" },
        "Quedate Señor": { ruta: "comunion/quedate-señor.html", tono: "DO" },
        "Quiero ser tu amigo Jesucristo": { ruta: "comunion/quiero-ser-tu-amigo-jesucristo.html", tono: "SOL" },
        "Renace la vida y el corazón": { ruta: "comunion/renace-la-vida-y-el-corazon.html", tono: "SOL" },
        "Sal y luz": { ruta: "comunion/sal-y-luz.html", tono: "SI" },
        "Sé en quién he puesto mi confianza": { ruta: "comunion/se-en-quien-he-puesto-mi-confianza.html", tono: "MI" },
        "Sentidos": { ruta: "comunion/sentidos.html", tono: "SOL" },
        "Será Dios": { ruta: "comunion/sera-dios.html", tono: "SOL" },
        "Si quieres te acompaño en el camino": { ruta: "comunion/si-quieres-te-acompaño-en-el-camino.html", tono: "DO" },
        "Siempre para ti": { ruta: "comunion/siempre-para-ti.html", tono: "RE" },
        "Sin fronteras": { ruta: "comunion/sin-fronteras.html", tono: "SOL" },
        "Somos JM, somos iglesia": { ruta: "comunion/somos-jm-somos-iglesia.html", tono: "SOL" },
        "Soñar": { ruta: "comunion/soñar.html", tono: "MI" },
        "Tu amor": { ruta: "comunion/tu-amor.html", tono: "LA" },
        "Una gota de agua": { ruta: "comunion/una-gota-de-agua.html", tono: "SOL" },
        "Ven Jesús de Nazareth": { ruta: "comunion/ven-jesus-de-nazareth.html", tono: "RE" },
        "Ven Pastor": { ruta: "comunion/ven-pastor.html", tono: "RE" },
        "Vengan y coman": { ruta: "comunion/vengan-y-coman.html", tono: "RE" },
        "Vida en abundancia": { ruta: "comunion/vida-en-abundancia.html", tono: "MI" },
        "Yo soy el mar": { ruta: "comunion/yo-soy-el-mar.html", tono: "SOL" }
    },
    "Meditación": {
        "A Él la Gloria": { ruta: "meditacion/a-el-la-gloria.html", tono: "SOL" },
        "Abramos": { ruta: "meditacion/abramos.html", tono: "RE" },
        "Al servicio de aquel": { ruta: "comunion/al-servicio-de-aquel.html", tono: "SOL" },
        "Alábenlo": { ruta: "meditacion/alabenlo.html", tono: "LA" },
        "Algo de paz": { ruta: "meditacion/algo-de-paz.html", tono: "RE" },
        "Alma de Cristo": { ruta: "meditacion/alma-de-cristo.html", tono: "LA" },
        "Alzar banderas": { ruta: "comunion/alzar-banderas.html", tono: "DO" },
        "Amanecer": { ruta: "meditacion/amanecer.html", tono: "FA" },
        "Amigo": { ruta: "meditacion/amigo.html", tono: "RE" },
        "Apareces": { ruta: "comunion/apareces.html", tono: "DO" },
        "Apóstol de Jesucristo": { ruta: "meditacion/apostol-de-jesucristo.html", tono: "LA" },
        "Cae el agua": { ruta: "meditacion/cae-el-agua.html", tono: "MI" },
        "Caminho de eternidade": { ruta: "meditacion/caminho-de-eternidade.html", tono: "RE" },
        "Cantaro niño": { ruta: "comunion/cantaro-niño.html", tono: "RE" },
        "Cara a cara": { ruta: "meditacion/cara-a-cara.html", tono: "LA" },
        "Cayado de amor": { ruta: "meditacion/cayado-de-amor.html", tono: "DO" },
        "Como antes, más que antes": { ruta: "comunion/como-antes-mas-que-antes.html", tono: "RE" },
        "Como un niño": { ruta: "comunion/como-un-niño.html", tono: "SOL" },
        "Con vos": { ruta: "comunion/con-vos.html", tono: "MI" },
        "Conozco tu corazón": { ruta: "meditacion/conozco-tu-corazon.html", tono: "SOL" },
        "Cristo calla": { ruta: "meditacion/cristo-calla.html", tono: "SOL" },
        "Cristo reina": { ruta: "meditacion/cristo-reina.html", tono: "DO" },
        "Cristo Rey": { ruta: "meditacion/cristo-rey.html", tono: "RE" },
        "Dame tus ojos": { ruta: "meditacion/dame-tus-ojos.html", tono: "DO" },
        "De Cirene": { ruta: "comunion/de-cirene.html", tono: "LA" },
        "Déjate": { ruta: "comunion/dejate.html", tono: "DO" },
        "Derrama": { ruta: "meditacion/derrama.html", tono: "DO" },
        "Digno de alabar": { ruta: "meditacion/digno-de-alabar.html", tono: "SOL" },
        "Dime Rey": { ruta: "meditacion/dime-rey.html", tono: "LA" },
        "El diario de María": { ruta: "marianos/el-diario-de-maria.html", tono: "LA" },
        "Él me miró": { ruta: "meditacion/el-me-miro.html", tono: "DO" },
        "El mismo huerto": { ruta: "meditacion/el-mismo-huerto.html", tono: "RE" },
        "El que muere por mi": { ruta: "comunion/el-que-muere-por-mi.html", tono: "DO" },
        "El sale a tu encuentro": { ruta: "comunion/el-sale-a-tu-encuentro.html", tono: "MI" },
        "En mi Getsemani": { ruta: "comunion/en-mi-getsemani.html", tono: "DO" },
        "En la palma de su mano": { ruta: "meditacion/en-la-palma-de-su-mano.html", tono: "RE" },
        "En ti": { ruta: "meditacion/en-ti.html", tono: "SOL" },
        "En ti descansar": { ruta: "meditacion/en-ti-descansar.html", tono: "SOL" },
        "En tu misericordia": { ruta: "meditacion/en-tu-misericordia.html", tono: "RE" },
        "En tus ojos": { ruta: "comunion/en-tus-ojos.html", tono: "SOL" },
        "Esa flor siempre de pie": { ruta: "meditacion/esa-flor-siempre-de-pie.html", tono: "SOL" },
        "Escúchame Dios": { ruta: "meditacion/escuchame-dios.html", tono: "SOL" },
        "Espíritu Santo": { ruta: "espiritu-santo/espiritu-santo.html", tono: "RE" },
        "Espíritu desciende": { ruta: "espiritu-santo/espiritu-desciende.html", tono: "RE" },
        "Estamos aquí": { ruta: "comunion/estamos-aqui.html", tono: "SOL" },
        "Extiende tu mano": { ruta: "meditacion/extiende-tu-mano.html", tono: "DO" },
        "Extranjeros": { ruta: "meditacion/extranjeros.html", tono: "DO" },
        "Ha sido largo el viaje": { ruta: "comunion/ha-sido-largo-el-viaje.html", tono: "MI" },
        "Hagase mi paz": { ruta: "comunion/hagase-mi-paz.html", tono: "MI" },
        "Hasta que el mundo arda por El": { ruta: "comunion/hasta-que-el-mundo-arda-por-el.html", tono: "LA" },
        "Hijo amado": { ruta: "meditacion/hijo-amado.html", tono: "SI" },
        "Huracán": { ruta: "meditacion/huracan.html", tono: "DO" },
        "Jesús": { ruta: "meditacion/jesus.html", tono: "DO" },
        "Jesús (Berit II)": { ruta: "meditacion/jesus-berit2.html", tono: "DO" },
        "La luz de Jesús": { ruta: "meditacion/la-luz-de-jesus.html", tono: "DO" },
        "La niña de tus ojos": { ruta: "comunion/la-niña-de-tus-ojos.html", tono: "MI" },
        "Labor del apostol": { ruta: "comunion/labor-del-apostol.html", tono: "DO" },
        "Lo que importa es el amor": { ruta: "meditacion/lo-que-importa-es-el-amor.html", tono: "RE" },
        "Magnificat (Portugués)": { ruta: "meditacion/magnificat.html", tono: "DO" },
        "Maranatha": { ruta: "espiritu-santo/maranatha.html", tono: "SOL" },
        "Maravillas hizo en mi": { ruta: "meditacion/maravillas-hizo-en-mi.html", tono: "DO" },
        "María tierra del Padre": { ruta: "comunion/maria-tierra-del-padre.html", tono: "LA" },
        "Me llamaste amigo": { ruta: "meditacion/me-llamaste-amigo.html", tono: "DO" },
        "¿Me quieres?": { ruta: "meditacion/me-quieres.html", tono: "MI" },
        "Mi 110%": { ruta: "meditacion/mi-110.html", tono: "FA" },
        "Mi alma descansa en ti": { ruta: "meditacion/mi-alma-descansa-en-ti.html", tono: "LA" },
        "Mi entrega a ti": { ruta: "meditacion/mi-entrega-a-ti.html", tono: "RE" },
        "Milagro de amor": { ruta: "meditacion/milagro-de-amor.html", tono: "SOL" },
        "Nada te turbe": { ruta: "meditacion/nada-te-turbe.html", tono: "RE" },
        "Nadie te ama como yo": { ruta: "meditacion/nadie-te-ama-como-yo.html", tono: "LA" },
        "No hay amor más grande": { ruta: "comunion/no-hay-amor-mas-grande.html", tono: "DO" },
        "No mueras hermano": { ruta: "meditacion/no-mueras-hermano.html", tono: "SOL" },
        "No os preocupeis": { ruta: "meditacion/no-os-preocupeis.html", tono: "SOL" },
        "No tienen vino": { ruta: "meditacion/no-tienen-vino.html", tono: "DO" },
        "Noche": { ruta: "meditacion/noche.html", tono: "FA" },
        "Oh Padre": { ruta: "ofertorio/oh-padre.html", tono: "DO" },
        "Oración de confianza": { ruta: "meditacion/oracion-de-confianza.html", tono: "DO" },
        "Permanecer en ti": { ruta: "meditacion/permanecer-en-ti.html", tono: "SOL" },
        "Pescador de hombres": { ruta: "comunion/pescador-de-hombres.html", tono: "DO" },
        "Por un solo momento": { ruta: "meditacion/por-un-solo-momento.html", tono: "DO" },
        "Puer et Pater": { ruta: "meditacion/puer-et-pater.html", tono: "RE" },
        "Que se abra el cielo": { ruta: "espiritu-santo/que-se-abra-el-cielo.html", tono: "MI" },
        "Quiero ser Santo": { ruta: "meditacion/quiero-ser-santo.html", tono: "FA" },
        "Quiero ser tu amigo Jesucristo": { ruta: "comunion/quiero-ser-tu-amigo-jesucristo.html", tono: "SOL" },
        "Renace la vida y el corazón": { ruta: "comunion/renace-la-vida-y-el-corazon.html", tono: "SOL" },
        "Sal y luz": { ruta: "comunion/sal-y-luz.html", tono: "SI" },
        "Sáname": { ruta: "meditacion/saname.html", tono: "RE" },
        "Señor de la paz": { ruta: "meditacion/señor-de-la-paz.html", tono: "RE" },
        "Será Dios": { ruta: "comunion/sera-dios.html", tono: "SOL" },
        "Si quieres te acompaño en el camino": { ruta: "comunion/si-quieres-te-acompaño-en-el-camino.html", tono: "DO" },
        "Si rasgaras": { ruta: "meditacion/si-rasgaras.html", tono: "SOL" },
        "Siempre has sido Tú": { ruta: "meditacion/siempre-has-sido-tu.html", tono: "LA" },
        "Siempre para ti": { ruta: "comunion/siempre-para-ti.html", tono: "RE" },
        "Sigueme": { ruta: "meditacion/sigueme.html", tono: "MI" },
        "Silencio fecundo": { ruta: "meditacion/silencio-fecundo.html", tono: "SOL" },
        "Solo por hoy": { ruta: "meditacion/solo-por-hoy.html", tono: "RE" },
        "Sopla": { ruta: "meditacion/sopla.html", tono: "RE" },
        "Stabat": { ruta: "meditacion/stabat.html", tono: "LA" },
        "Subido al sicomoro": { ruta: "meditacion/subido-al-sicomoro.html", tono: "RE" },
        "Supe que me amabas": { ruta: "meditacion/supe-que-me-amabas.html", tono: "LA" },
        "Surge valentía": { ruta: "meditacion/surge-valentia.html", tono: "SOL" },
        "También hoy": { ruta: "meditacion/tambien-hoy.html", tono: "DO" },
        "Te alabo": { ruta: "meditacion/te-alabo.html", tono: "RE" },
        "Te encontré (Mario Gazal)": { ruta: "meditacion/te-encontre.html", tono: "DO" },
        "Tempestad": { ruta: "meditacion/tempestad.html", tono: "SOL" },
        "Torrente de Vida": { ruta: "meditacion/torrente-de-vida.html", tono: "DO" },
        "Transforma mi casa en tu hogar": { ruta: "meditacion/transforma-mi-casa-en-tu-hogar.html", tono: "FA" },
        "Transformación en Pentecostes": { ruta: "meditacion/transformacion-en-pentecostes.html", tono: "MI" },
        "Tu luz (Signos de amor)": { ruta: "meditacion/tu-luz.html", tono: "LA" },
        "Tu modo": { ruta: "meditacion/tu-modo.html", tono: "LA" },
        "Tu voluntad": { ruta: "meditacion/tu-voluntad.html", tono: "LA" },
        "Tu voluntad (Servus Mariae)": { ruta: "meditacion/tu-voluntad-servus.html", tono: "SI" },
        "Una cuerda menos": { ruta: "meditacion/una-cuerda-menos.html", tono: "LA" },
        "Ven Espíritu de amor": { ruta: "espiritu-santo/ven-espiritu-de-amor.html", tono: "RE" },
        "Ven Espíritu Divino": { ruta: "espiritu-santo/ven-espiritu-divino.html", tono: "DO" },
        "Ven y sígueme": { ruta: "meditacion/ven-y-sigueme.html", tono: "LA" },
        "Ven y verás": { ruta: "meditacion/ven-y-veras.html", tono: "DO" },
        "Vengo a adorarte": { ruta: "meditacion/vengo-a-adorarte.html", tono: "RE" },
        "Verás cosas mayores": { ruta: "meditacion/veras-cosas-mayores.html", tono: "DO" },
        "Vivir amando": { ruta: "meditacion/vivir-amando.html", tono: "RE" },
        "Vuelve a mi": { ruta: "meditacion/vuelve-a-mi.html", tono: "SOL" },
        "Vuelvo a ti": { ruta: "meditacion/vuelvo-a-ti.html", tono: "SOL" }
    },
    "Salida": {
        "Alma Misionera": { ruta: "entrada/alma-misionera.html", tono: "MI" },
        "Alzar banderas": { ruta: "comunion/alzar-banderas.html", tono: "DO" },
        "Avanza Reina": { ruta: "salida/avanza-reina.html", tono: "RE" },
        "Ave María": { ruta: "salida/ave-maria.html", tono: "MI" },
        "Dios te salve": { ruta: "salida/dios-te-salve.html", tono: "SOL" },
        "Este es mi hogar": { ruta: "salida/este-es-mi-hogar.html", tono: "RE" },
        "Hay un río de vida": { ruta: "salida/hay-un-rio-de-vida.html", tono: "RE" },
        "Ignis Mariae": { ruta: "salida/ignis-mariae.html", tono: "LA" },
        "Junto a tí María": { ruta: "salida/junto-a-ti-maria.html", tono: "RE" },
        "La de siempre": { ruta: "salida/la-de-siempre.html", tono: "SOL" },
        "Mar adentro": { ruta: "salida/mar-adentro.html", tono: "MI" },
        "María de la Alianza": { ruta: "salida/maria-de-la-alianza.html", tono: "LA" },
        "Misioneros": { ruta: "salida/misioneros.html", tono: "LA" },
        "Reina de mi corazón": { ruta: "salida/reina-de-mi-corazon.html", tono: "RE" },
        "Sobre el mar": { ruta: "salida/sobre-el-mar.html", tono: "DO" },
        "Somos jm, somos iglesia": { ruta: "comunion/somos-jm-somos-iglesia.html", tono: "SOL" },
        "Voces de Esperanza": { ruta: "espiritu-santo/voces-de-esperanza.html", tono: "MI" }
    },
    "Marianos": {
        "A tanto amor": { ruta: "marianos/a-tanto-amor.html", tono: "SOL" },
        "Abrazada a ti en tu cruz": { ruta: "marianos/abrazada-a-ti-en-tu-cruz.html", tono: "SOL" },
        "Avanza Reina": { ruta: "salida/avanza-reina.html", tono: "RE" },
        "Ave María": { ruta: "salida/ave-maria.html", tono: "MI" },
        "Dios te salve": { ruta: "salida/dios-te-salve.html", tono: "SOL" },
        "El diario de María": { ruta: "marianos/el-diario-de-maria.html", tono: "LA" },
        "En tus ojos": { ruta: "comunion/en-tus-ojos.html", tono: "SOL" },
        "Hasta que el mundo arda por Él": { ruta: "comunion/hasta-que-el-mundo-arda-por-el.html", tono: "LA" },
        "Junto a ti María": { ruta: "salida/junto-a-ti-maria.html", tono: "RE" },
        "Juremos con gloria morir": { ruta: "comunion/juremos-con-gloria-morir.html", tono: "SOL" },
        "La de siempre": { ruta: "salida/la-de-siempre.html", tono: "SOL" },
        "Magnificat (Portugués)": { ruta: "meditacion/magnificat.html", tono: "DO" },
        "María de la alianza": { ruta: "salida/maria-de-la-alianza.html", tono: "LA" },
        "María está pasando por aquí": { ruta: "marianos/maria-esta-pasando-por-aqui.html", tono: "DO" },
        "María Madre": { ruta: "comunion/maria-madre.html", tono: "MI" },
        "María tierra del Padre": { ruta: "comunion/maria-tierra-del-padre.html", tono: "LA" },
        "María Vai": { ruta: "comunion/maria-vai.html", tono: "DO" },
        "Nuestra Alianza": { ruta: "comunion/nuestra-alianza.html", tono: "MI" },
        "Oración de consagración": { ruta: "marianos/oracion-de-consagracion.html", tono: "SOL" },
        "Para que todos tengan vida": { ruta: "comunion/para-que-todos-tengan-vida.html", tono: "DO" },
        "Reina de mi corazón": { ruta: "salida/reina-de-mi-corazon.html", tono: "RE" },
        "Reina y Madre": { ruta: "marianos/reina-y-madre.html", tono: "SOL" },
        "Se llama María": { ruta: "marianos/se-llama-maria.html", tono: "DO" },
        "Tu amor": { ruta: "comunion/tu-amor.html", tono: "LA" }
    },
    "Envío": {
        "Alma Misionera": { ruta: "entrada/alma-misionera.html", tono: "mi" },
        "Alzar banderas": { ruta: "comunion/alzar-banderas.html", tono: "DO" },
        "Avanza Reina": { ruta: "salida/avanza-reina.html", tono: "RE" },
        "Deja que nazca": { ruta: "entrada/deja-que-nazca.html", tono: "MI" },
        "Estandarte": { ruta: "comunion/estandarte.html", tono: "RE" },
        "Hay un río de vida": { ruta: "salida/hay-un-rio-de-vida.html", tono: "RE" },
        "Ignis Mariae": { ruta: "salida/ignis-mariae.html", tono: "LA" },
        "Mar adentro": { ruta: "salida/mar-adentro.html", tono: "LA" },
        "Misioneros": { ruta: "salida/misioneros.html", tono: "LA" },
        "Salmo 28": { ruta: "salmos/salmo-28.html", tono: "LA" },
        "Se llama María": { ruta: "marianos/se-llama-maria.html", tono: "DO" },
        "Sobre el mar": { ruta: "salida/sobre-el-mar.html", tono: "DO" },
        "Somos JM, somos iglesia": { ruta: "comunion/somos-jm-somos-iglesia.html", tono: "SOL" },
        "Voces de Esperanza": { ruta: "espiritu-santo/voces-de-esperanza.html", tono: "MI" }
    },
    "Espíritu Santo": {
        "Derrama": { ruta: "meditacion/derrama.html", tono: "DO" },
        "Espíritu Santo": { ruta: "espiritu-santo/espiritu-santo.html", tono: "RE" },
        "Espíritu desciende": { ruta: "espiritu-santo/espiritu-desciende.html", tono: "RE" },
        "Fuego Santo": { ruta: "espiritu-santo/fuego-santo.html", tono: "DO" },
        "Maranathá": { ruta: "espiritu-santo/maranatha.html", tono: "DO" },
        "Que se abra el cielo": { ruta: "espiritu-santo/que-se-abra-el-cielo.html", tono: "MI" },
        "Ven Espíritu de Amor": { ruta: "espiritu-santo/ven-espiritu-de-amor.html", tono: "RE" },
        "Ven Espíritu Divino": { ruta: "espiritu-santo/ven-espiritu-divino.html", tono: "DO" },
        "Ven Espíritu Santo": { ruta: "espiritu-santo/ven-espiritu-santo.html", tono: "RE" },
        "Viento de Dios": { ruta: "espiritu-santo/viento-de-dios.html", tono: "SOL" },
        "Voces de Esperanza": { ruta: "espiritu-santo/voces-de-esperanza.html", tono: "MI" }
    },
    "Adoración": {
        "A Él la Gloria": { ruta: "meditacion/a-el-la-gloria.html", tono: "SOL" },
        "Abre": { ruta: "comunion/abre.html", tono: "LA" },
        "Alabado sea el Santísimo": { ruta: "adoracion/alabado-sea-el-santisimo.html", tono: "DO" },
        "Alábenlo": { ruta: "meditacion/alabenlo.html", tono: "LA" },
        "Algo de paz": { ruta: "meditacion/algo-de-paz.html", tono: "RE" },
        "Alma de Cristo": { ruta: "meditacion/alma-de-cristo.html", tono: "LA" },
        "Caminho de eternidade": { ruta: "meditacion/caminho-de-eternidade.html", tono: "RE" },
        "Camino, Verdad y Vida": { ruta: "comunion/camino-verdad-y-vida.html", tono: "DO" },
        "Cántaro Niño": { ruta: "comunion/cantaro-niño.html", tono: "RE" },
        "Cara a cara": { ruta: "meditacion/cara-a-cara.html", tono: "LA" },
        "Con vos": { ruta: "comunion/con-vos.html", tono: "MI" },
        "Conozco tu corazón": { ruta: "meditacion/conozco-tu-corazon.html", tono: "SOL" },
        "Cristo calla": { ruta: "meditacion/cristo-calla.html", tono: "SOL" },
        "Cristo reina": { ruta: "meditacion/cristo-reina.html", tono: "DO" },
        "Cristo Rey": { ruta: "meditacion/cristo-rey.html", tono: "RE" },
        "Dame tus ojos": { ruta: "meditacion/dame-tus-ojos.html", tono: "DO" },
        "Déjate": { ruta: "comunion/dejate.html", tono: "DO" },
        "Derrama": { ruta: "meditacion/derrama.html", tono: "DO" },
        "Digno de alabar": { ruta: "meditacion/digno-de-alabar.html", tono: "SOL" },
        "Dime Rey": { ruta: "meditacion/dime-rey.html", tono: "LA" },
        "Él me miró": { ruta: "meditacion/el-me-miro.html", tono: "DO" },
        "El que muere por mi": { ruta: "comunion/el-que-muere-por-mi.html", tono: "DO" },
        "El sale a tu encuentro": { ruta: "comunion/el-sale-a-tu-encuentro.html", tono: "MI" },
        "En ti descansar": { ruta: "meditacion/en-ti-descansar.html", tono: "SOL" },
        "En tu misericordia": { ruta: "meditacion/en-tu-misericordia.html", tono: "RE" },
        "En tus ojos": { ruta: "comunion/en-tus-ojos.html", tono: "SOL" },
        "Escúchame Dios": { ruta: "meditacion/escuchame-dios.html", tono: "SOL" },
        "Espíritu Santo": { ruta: "espiritu-santo/espiritu-santo.html", tono: "RE" },
        "Espíritu desciende": { ruta: "espiritu-santo/espiritu-desciende.html", tono: "RE" },
        "Esto que soy, esto te doy": { ruta: "ofertorio/esto-que-soy-esto-te-doy.html", tono: "DO" },
        "Extiende tu mano": { ruta: "meditacion/extiende-tu-mano.html", tono: "DO" },
        "Ha sido largo el viaje": { ruta: "comunion/ha-sido-largo-el-viaje.html", tono: "MI" },
        "Hijo amado": { ruta: "meditacion/hijo-amado.html", tono: "SI" },
        "Jesús": { ruta: "meditacion/jesus.html", tono: "DO" },
        "Jesús (Berit II)": { ruta: "meditacion/jesus-berit2.html", tono: "DO" },
        "Maranatha": { ruta: "espiritu-santo/maranatha.html", tono: "SOL" },
        "¿Me quieres?": { ruta: "meditacion/me-quieres.html", tono: "MI" },
        "Mi 110%": { ruta: "meditacion/mi-110.html", tono: "FA" },
        "Mi alma descansa en ti": { ruta: "meditacion/mi-alma-descansa-en-ti.html", tono: "LA" },
        "Mi entrega a ti": { ruta: "meditacion/mi-entrega-a-ti.html", tono: "RE" },
        "Milagro de amor": { ruta: "meditacion/milagro-de-amor.html", tono: "SOL" },
        "Nada te turbe": { ruta: "meditacion/nada-te-turbe.html", tono: "RE" },
        "Nadie te ama como yo": { ruta: "meditacion/nadie-te-ama-como-yo.html", tono: "LA" },
        "No hay amor más grande": { ruta: "comunion/no-hay-amor-mas-grande.html", tono: "DO" },
        "No mueras hermano": { ruta: "meditacion/no-mueras-hermano.html", tono: "SOL" },
        "Noche": { ruta: "meditacion/noche.html", tono: "FA" },
        "Permanecer en ti": { ruta: "meditacion/permanecer-en-ti.html", tono: "SOL" },
        "Que se abra el cielo": { ruta: "espiritu-santo/que-se-abra-el-cielo.html", tono: "MI" },
        "Quiero ser Santo": { ruta: "meditacion/quiero-ser-santo.html", tono: "FA" },
        "Señor de la paz": { ruta: "meditacion/señor-de-la-paz.html", tono: "RE" },
        "Si quieres te acompaño en el camino": { ruta: "comunion/si-quieres-te-acompaño-en-el-camino.html", tono: "DO" },
        "Si rasgaras": { ruta: "meditacion/si-rasgaras.html", tono: "SOL" },
        "Siempre para ti": { ruta: "comunion/siempre-para-ti.html", tono: "RE" },
        "Sígueme": { ruta: "meditacion/sigueme.html", tono: "MI" },
        "Silencio fecundo": { ruta: "meditacion/silencio-fecundo.html", tono: "SOL" },
        "Sopla": { ruta: "meditacion/sopla.html", tono: "RE" },
        "Stabat": { ruta: "meditacion/stabat.html", tono: "LA" },
        "Supe que me amabas": { ruta: "meditacion/supe-que-me-amabas.html", tono: "LA" },
        "Surge valentía": { ruta: "meditacion/surge-valentia.html", tono: "SOL" },
        "También hoy": { ruta: "meditacion/tambien-hoy.html", tono: "DO" },
        "Te alabo": { ruta: "meditacion/te-alabo.html", tono: "RE" },
        "Te encontré": { ruta: "meditacion/te-encontre.html", tono: "DO" },
        "Tempestad": { ruta: "meditacion/tempestad.html", tono: "SOL" },
        "Transformación en Pentecostés": { ruta: "meditacion/transformacion-en-pentecostes.html", tono: "MI" },
        "Tu luz (Signos de amor)": { ruta: "meditacion/tu-luz.html", tono: "LA" },
        "Tu voluntad (Servus Mariae)": { ruta: "meditacion/tu-voluntad-servus.html", tono: "SI" },
        "Ven Espíritu de amor": { ruta: "espiritu-santo/ven-espiritu-de-amor.html", tono: "RE" },
        "Ven Jesús de Nazareth": { ruta: "comunion/ven-jesus-de-nazareth.html", tono: "RE" },
        "Ven y verás": { ruta: "meditacion/ven-y-veras.html", tono: "DO" },
        "Vengo a adorarte": { ruta: "meditacion/vengo-a-adorarte.html", tono: "RE" }
    },
    "JM":{
        "Alzar banderas": { ruta: "comunion/alzar-banderas.html", tono: "DO" },
        "Corazón de Fuego": { ruta: "jm/corazon-de-fuego.html", tono: "MI" },
        "Estandarte": { ruta: "comunion/estandarte.html", tono: "RE" },
        "Hasta que el mundo arda por Él": { ruta: "comunion/hasta-que-el-mundo-arda-por-el.html", tono: "LA" },
        "Herencia (José Engling)": { ruta: "jm/herencia.html", tono: "DO" },
        "Juremos con gloria morir": { ruta: "comunion/juremos-con-gloria-morir.html", tono: "SOL" },
        "Mi 110%": { ruta: "meditacion/mi-110.html", tono: "FA" },
        "Oración de Franz Reinisch": { ruta: "jm/oracion-de-franz-reinisch.html", tono: "SOL" },
        "Pasión que transforma": { ruta: "comunion/pasion-que-transforma.html", tono: "RE" },
        "Puer et Pater": { ruta: "meditacion/puer-et-pater.html", tono: "RE" },
        "Somos JM, somos iglesia": { ruta: "comunion/somos-jm-somos-iglesia.html", tono: "SOL" },
        "Stabat": { ruta: "meditacion/stabat.html", tono: "LA" }
    },
    "JF":{
        "Generación fundadora": {ruta:"jf/generacion-fundadora.html", tono: "SOL"},
        "Talita Kum": {ruta:"jf/talita-kum.html", tono: "DO"}
    }
}